version: "3"
services:
  db:
    image: mongo:7-jammy
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'"]
    networks: [notes-app]
  api:
    build:
      dockerfile: Dockerfile
      context: api
    ports:
      - 8000:8000
    environment:
      MONGODB_URI: db:27017
    networks: [notes-app]
    depends_on:
      db:
        condition: service_healthy
  front:
    build:
      dockerfile: Dockerfile
      context: front
    restart: always
    environment:
      API_URL: http://localhost:8000
    ports:
      - 5000:80
    networks: [notes-app]
    depends_on:
      api:
        condition: service_healthy

networks:
  notes-app: