apiVersion: v1
kind: Namespace
metadata:
  name: notes-demo-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: notes-demo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: notes-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ghcr.io/blakelead/notes-demo-app-front:latest
        env:
        - name: API_URL
          value: http://api:8000
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: notes-demo-app
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: notes-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/blakelead/notes-demo-app-api:latest
        env:
        - name: MONGODB_URI
          value: mongodb.notes-demo-db:27017
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: notes-demo-app
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: notes-demo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7-jammy
        livenessProbe:
          exec:
            command: ["mongosh", "--eval", "db.runCommand({ping:1})"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: notes-demo-db
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
