name: Publish Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Front Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./front
        push: true
        tags: ghcr.io/blakelead/notes-demo-app-front:latest
    - name: Build and Push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./api
        push: true
        tags: ghcr.io/blakelead/notes-demo-app-api:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
